"""Root pytest conftest.

Sole job: pick the pure-Python protobuf backend BEFORE anything imports
``google.protobuf``. The optional ``etcd3`` client (0.12.0) ships ``_pb2.py``
stubs generated by an ancient ``protoc`` that the modern C/upb protobuf backend
(protobuf >= 4) refuses to load ("Descriptors cannot be created directly").
protobuf reads ``PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION`` exactly once, at its
first import, so this MUST run before any protobuf-touching module is imported.
pytest imports the root conftest before collecting test modules, so setting it
here fixes the whole suite (see tests/test_etcd_integration.py for the etcd
integration tests that depend on it).

This only affects Python's protobuf *implementation selection*; it is a no-op if
protobuf was already imported, in which case the etcd tests skip with guidance.
"""
import os

os.environ.setdefault("PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION", "python")
